name: "Render"

on:
  push:
    branches:
      - master

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile cv.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: cv.pdf
      - name: Commit rendered CV
        run: |
          git config --global user.name 'github-actions bot'
          git config --global user.email 'katenika158@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add cv.pdf
          git commit -m "Publish rendered CV"
          git push
  render_ru:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile cv_ru.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv_ru.tex
      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF_ru
          path: cv_ru.pdf
      - name: Commit rendered CV
        run: |
          git config --global user.name 'github-actions bot'
          git config --global user.email 'katenika158@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add cv_ru.pdf
          git commit -m "Publish rendered ru CV"
          git push

